-- ============================================================
-- 消费物化视图：Kafka 引擎表 → 明细表（导入打平层）
-- 设计依据：clickhouse/docs/modifications/2026-10-01-clickhouse-dock/design-changes.md
-- ============================================================
-- 本 MV 等价 Doris Routine Load 的 COLUMNS 映射：
--   * UTC 墙钟：toDateTime(timestamp, 'UTC') 对应 Doris 的
--     DATE_SUB(FROM_UNIXTIME(timestamp), INTERVAL TIMESTAMPDIFF(SECOND, UTC_TIMESTAMP(), NOW()) SECOND)；
--   * apikeytags 打平：JSONExtractString(ai_apikeytags, 'levelN', 'tagname/tagvalue')
--     对应 json_unquote(json_extract(ai_apikeytags, '$.levelN.tagname/tagvalue'))；
--     空对象/缺失路径返回 ''（Doris 侧为 NULL，明细查询谓词 `!= ''` 行为一致）；
--   * 限流打平：取 ai_rate_limit_hits 首个元素的具名字段，空数组经 length 守卫返回 '';
--   * ai_apikeytags / timestamp 不投影，不落明细表（同 Doris 侧源字段不落表）；
--   * Nested 列（req_headers/res_headers）在 MV 按名列匹配时须展开为物理子列
--     req_headers.key / req_headers.value（Nested 整体名是虚拟投影，非物理列）。
-- ============================================================
CREATE MATERIALIZED VIEW IF NOT EXISTS ${CLICKHOUSE_DATABASE}.bfe_ai_log_load_mv
TO ${CLICKHOUSE_DATABASE}.bfe_ai_request_log AS
SELECT
    hostid,
    toDateTime(`timestamp`, 'UTC') AS log_time,
    ai_apikey_id,
    ai_requested_model,
    logid,
    product,
    log_tag,
    client_ip,
    client_network,
    is_trust_src_ip,
    req_num,
    session_id,
    bfe_ip,
    sock_src_ip,
    vip,
    vip6,
    err_code,
    err_msg,
    proto,
    header_host,
    origin_uri,
    final_uri,
    method,
    content_type,
    x_forward_for,
    accept_language,
    authorization,
    transfer_encoding,
    referrer,
    user_agent,
    delegation,
    uid,
    cookie,
    `req_headers.key`,
    `req_headers.value`,
    req_header_len,
    req_body_len,
    cluster,
    sub_cluster,
    backend_info,
    backend_retry,
    res_status_code,
    res_header_len,
    res_body_len,
    res_content_type,
    res_location,
    res_transfer_encoding,
    `res_headers.key`,
    `res_headers.value`,
    all_time,
    read_client_time,
    cluster_serve_time,
    backend_serve_time,
    write_client_time,
    connect_backend_time,
    proxy_delay_time,
    session_offset_time,
    JSONExtractString(ai_apikeytags, 'level1', 'tagname') AS level1Name,
    JSONExtractString(ai_apikeytags, 'level1', 'tagvalue') AS level1,
    JSONExtractString(ai_apikeytags, 'level2', 'tagname') AS level2Name,
    JSONExtractString(ai_apikeytags, 'level2', 'tagvalue') AS level2,
    JSONExtractString(ai_apikeytags, 'level3', 'tagname') AS level3Name,
    JSONExtractString(ai_apikeytags, 'level3', 'tagvalue') AS level3,
    JSONExtractString(ai_apikeytags, 'level4', 'tagname') AS level4Name,
    JSONExtractString(ai_apikeytags, 'level4', 'tagvalue') AS level4,
    JSONExtractString(ai_apikeytags, 'level5', 'tagname') AS level5Name,
    JSONExtractString(ai_apikeytags, 'level5', 'tagvalue') AS level5,
    ai_target_model,
    ai_stream,
    ai_input_tokens,
    ai_output_tokens,
    ai_total_tokens,
    ai_cache_read_tokens,
    ai_cache_write_tokens,
    ai_audio_input_tokens,
    ai_audio_output_tokens,
    ai_image_count,
    ai_ttft_us,
    ai_tpot_us,
    ai_provider,
    ai_protocol,
    ai_mode,
    ai_retry_count,
    ai_cost_value,
    ai_cost_currency,
    ai_route_rule_hits,
    ai_cluster_key_names,
    ai_rate_limit_hits,
    if(length(ai_rate_limit_hits) >= 1, (ai_rate_limit_hits[1]).rate_limit_policy_id, '') AS rate_limit_policy_id,
    if(length(ai_rate_limit_hits) >= 1, (ai_rate_limit_hits[1]).rate_limit_type, '')      AS rate_limit_type,
    if(length(ai_rate_limit_hits) >= 1, (ai_rate_limit_hits[1]).rule_names[1], '')        AS rate_limit_rule_name,
    ai_auth_reject_reason,
    ai_auth_reject_quota_plans,
    ai_auth_hit_quota_plans,
    ai_cache_status,
    mirror_hit,
    mirror_cluster,
    ai_intent_question,
    ai_intent_answer,
    ai_intent_confidence,
    ai_intent_source,
    ai_intent_latency_us,
    ai_intent_cache_hit,
    ai_intent_questions_version
FROM ${CLICKHOUSE_DATABASE}.bfe_ai_log_kafka;
