-- ============================================================
-- Kafka 引擎暂存表：schema 与 mod_kafka 输出的 JSON 消息同构（80 字段）
-- 设计依据：clickhouse/docs/modifications/2026-10-01-clickhouse-dock/design-changes.md
-- ============================================================
-- 机制说明（等价 Doris Routine Load 的 Kafka 消费端）：
--   * 本表只做消息暂存，不落盘存储（Kafka 引擎表无实际数据）；
--   * 消费 MV（bfe_ai_log_load_mv）从本表读取消息，完成 JSON 打平与 UTC 换算后
--     写入明细表 bfe_ai_request_log；
--   * input_format_skip_unknown_fields = 1：PB/log-reader 新增字段先于本表 DDL
--     到达时被跳过而不是报错，保证消费不中断；
--   * ai_apikeytags 为 JSON 对象，以 ClickHouse JSON 类型承载，仅在 MV 内
--     经 JSONExtractString 打平（level1~level5 十列），源对象不落明细表；
--   * kafka_group_name 必须与 Doris / StarRocks 链路的消费组不同（位点独立）。
-- ============================================================
CREATE TABLE IF NOT EXISTS ${CLICKHOUSE_DATABASE}.bfe_ai_log_kafka
(
    `logid`                   UInt64,
    `timestamp`               Int64 COMMENT 'epoch 秒，MV 内换算为 UTC 墙钟 log_time',
    `product`                 String,
    `log_tag`                 String,
    `hostid`                  String,
    `client_ip`               String,
    `client_network`          String,
    `is_trust_src_ip`         UInt8,
    `req_num`                 Int32,
    `session_id`              Int64,
    `bfe_ip`                  String,
    `sock_src_ip`             String,
    `vip`                     String,
    `vip6`                    String,
    `err_code`                String,
    `err_msg`                 Nullable(String),
    `req_header_len`          Int32,
    `req_body_len`            Int32,
    `proto`                   String,
    `header_host`             String,
    `origin_uri`              String,
    `final_uri`               String,
    `method`                  String,
    `content_type`            String,
    `x_forward_for`           String,
    `accept_language`         String,
    `authorization`           String,
    `transfer_encoding`       String,
    `referrer`                String,
    `user_agent`              String,
    `delegation`              String,
    `uid`                     String,
    `cookie`                  String,
    `req_headers`             Nested(`key` String, `value` String),
    `cluster`                 String,
    `sub_cluster`             String,
    `backend_info`            String,
    `backend_retry`           Int8,
    `res_status_code`         Int16,
    `res_header_len`          Int32,
    `res_body_len`            Int32,
    `res_content_type`        String,
    `res_location`            String,
    `res_transfer_encoding`   String,
    `res_headers`             Nested(`key` String, `value` String),
    `all_time`                Int32,
    `read_client_time`        Int32,
    `cluster_serve_time`      Int32,
    `backend_serve_time`      Int32,
    `write_client_time`       Int32,
    `connect_backend_time`    Int32,
    `proxy_delay_time`        Int32,
    `session_offset_time`     Int32,
    `ai_apikey_id`            String,
    `ai_apikeytags`           JSON COMMENT 'API Key 标签 JSON 对象，仅用于打平求值',
    `ai_requested_model`      String,
    `ai_target_model`         String,
    `ai_stream`               UInt8,
    `ai_input_tokens`         Int64,
    `ai_output_tokens`        Int64,
    `ai_total_tokens`         Int64,
    `ai_cache_read_tokens`    Int64,
    `ai_cache_write_tokens`   Int64,
    `ai_audio_input_tokens`   Int64,
    `ai_audio_output_tokens`  Int64,
    `ai_image_count`          Int64,
    `ai_ttft_us`              Int64,
    `ai_tpot_us`              Int64,
    `ai_provider`             String,
    `ai_protocol`             String,
    `ai_mode`                 String,
    `ai_retry_count`          Int32,
    `ai_cost_value`           Int64,
    `ai_cost_currency`        String,
    `ai_route_rule_hits`      Array(Tuple(rule_owner String, rule_owner_type String, rule_name String)),
    `ai_cluster_key_names`    Array(Tuple(cluster_name String, key_name String)),
    `ai_rate_limit_hits`      Array(Tuple(rate_limit_policy_id String, rate_limit_type String, rule_names Array(String))),
    `ai_auth_reject_reason`   String,
    `ai_auth_reject_quota_plans` Array(String),
    `ai_auth_hit_quota_plans` Array(String),
    `ai_cache_status`         String,
    `mirror_hit`              UInt8,
    `mirror_cluster`          String,
    `ai_intent_question`      String,
    `ai_intent_answer`        String,
    `ai_intent_confidence`    Nullable(Float64),
    `ai_intent_source`        String,
    `ai_intent_latency_us`    Nullable(Int64),
    `ai_intent_cache_hit`     Nullable(UInt8),
    `ai_intent_questions_version` String
)
ENGINE = Kafka
SETTINGS
    kafka_broker_list = '${KAFKA_BROKER_LIST}',
    kafka_topic_list = '${KAFKA_TOPIC}',
    kafka_group_name = '${KAFKA_GROUP_ID}',
    kafka_format = 'JSONEachRow',
    input_format_skip_unknown_fields = 1,
    kafka_num_consumers = 3;
